### ISSUE TITLE
Make jump instructions take a self+0 relative jump

### ISSUE THREAD

**Issue by rwy7** [b9org/b9#112]
Jump instructions have the target encoded as a relative offset in the immediate. This offset is relative to the current offset + 1. So for example, `JMP 0` is an unconditional jump forwards. This doesn't make much sense, as the offset is signed, and a `JMP -1` is an infinite loop. It probably makes more sense to just use the offset as-is. It's easier to work with and clearer to understand.

This would require a change in the front end, interpreter, and compiler.

**Comment by youngar** [comment]
This is the standard way jmp works for assembly languages.  I know it doesn't make sense, but I strongly vote to keep it this way.

**Comment by rwy7** [comment]
alright, fair enough.
