### ISSUE TITLE
Stop using dlsym

### ISSUE THREAD

**Issue by youngar** [b9org/b9#29]
We use dlsym to load the bytecode object files, and to dynamically link native functions from those bytecodes.  The reason we want to remove this to make the code base more portable.

We are using dlsym to find the locations of the bytecode entry points inside of an elf (or platform format) file. To remove its usage from the compiled files, we have to come up with out own binary format of these files, and write functions for reading and writing to them.  We can then call these functions directly from b9.js to create bytecode object files, instead of relying on gcc and ld to create the elf files for us.

We use dlsym to load native functions arbitrarily as bytecode object files demand.  We can remove this capability from base9, and change our implementation of base9 internal native functions.

**Comment by youngar** [comment]
I think that the second task of removing primitives from base9 is much easier.  

I think creating a new binary format for the object files might be a lot of work.  Possibly we can keep both methods of loading object files around for a bit (i.e. have an elf loader and b9object loader).

**Comment by rwy7** [comment]
Completed with the new module format.
