### ISSUE TITLE
Pass user-defined arguments to the mainFunction

### ISSUE THREAD

**Issue by rwy7** [b9org/b9#47]
We should provide a syntax to pass function arguments through the b9run CLI.

The syntax I'm suggesting is:
```
b9run [--] [<module> [<function> [<arg>....]]]
```

The `VirtualMachine::run` function will need to be expanded to accept an optional vector of arguments to initialize the operand stack with. Currently, `VirtualMachine::run` will push random integer args onto the stack, this code should probably be removed.

b9run would parse any extra argv to construct the argument vector.

`VirtualMachine::run`  should also check that the argument count is correct. The argument count is stored in the `FunctionSpec` ie `module_->functions[index]`.

Maybe as a first pass, we only accept integer arguments.

We could add support for strings, by having b9run add the string arguments to the module's string table, after the module has been loaded, then push the string addresses on the operand stack. The issue is deciding, when is an arg a string, and when is it a number.

**Comment by arianneb** [comment]
WIP

**Comment by youngar** [comment]
Syntax looks good.  I'm not sure about argument parsing, as a very first pass i would say don't worry about it.  I would consider never parsing the arguments, it doesn't provide much value to this project.
Edit: I didn't read very closely, and I missed the point of the issue.  Do we have some need for passing arguments to the program?

**Comment by rwy7** [comment]
We thought it might be useful for demonstration or testing.

**Comment by youngar** [comment]
Okay, sounds good to me.  It should be pretty easy to send integers to b9main.  Node handles the cli args like this: https://nodejs.org/docs/latest/api/process.html#process_process_argv

**Comment by arianneb** [comment]
done. @rwy0717 @youngar

**Comment by rwy7** [comment]
closed by #69
