### ISSUE TITLE
Print the result of calling the mainFunction

### ISSUE THREAD

**Issue by rwy7** [b9org/b9#48]
Currently, b9run discards the final returned result of the b9 program. I think it would be nice to print out the result before exiting.

Every function in b9 returns a value. This includes whichever main function is run. `VirtualMachine::run`will return the result of calling the main function. The `run(const RunConfig&)` function in b9run should be updated to print the result of calling `VirtualMachine::run` instead of discarding it.

Alternatively, we could use the result as the return code for the b9run program

**Comment by arianneb** [comment]
done
