### ISSUE TITLE
Write a factorial test program

### ISSUE THREAD

**Issue by xliang6** [b9org/b9#68]
As mentioned in [the b9 presentation](https://github.com/youngar/Base9/blob/master/CUSEC%202017%20-%20Buildering%20a%20JIT.pdf), we should create a factorial bench program to demonstrate multiply opcode.

**Comment by youngar** [comment]
There is one in `./test/fib.src`, needs work for benching

**Comment by xliang6** [comment]
@youngar Which branch is it in? Thanks.

**Comment by youngar** [comment]
It is in the `next` branch.  In the `master` branch, there is factorial written in [raw bytecodes]( https://github.com/youngar/Base9/blob/master/bench.cpp),

Either way, a factorial bench is pretty easy to write from scratch.  Do we want to run recursive or iterative fib?

**Comment by youngar** [comment]
I'm going crazy today, I thought you were looking for a fibonacci benchmark.  Here is the factorial from the slides:
``` js
function factorial(a) {
  if (a == 0)
    return 1;

  return a * factorial(a - 1);
}
```

**Comment by xliang6** [comment]
No worries. We just have to add it as a test in the next branch.

**Comment by xliang6** [comment]
Closing this issue -- factorial test was added. However we are using addition (+) as opposed to multiplication (*) since the CASCON tutorial was to teach students to add multiplication, i.e. multiplication opcode was not supported prior to the workshop.
