### ISSUE TITLE
Merge next into master

### ISSUE THREAD

**Issue by rwy7** [b9org/b9#72]
We'll probably have to reset the master branch. Also, maybe we want to backup the master branch as `stable`?

**Comment by jduimovich** [comment]
I think we should back it.

Using "stable" implies it will be updated with the stable version over time which if that is the plan, would be fine but then you also need a different name for each of the stable versions.  Call it "stable-dd-mm-yy" so you can track the ones used in courses etc. Any naming scheme is fine, as long as you can fine stuff by logical name.

**Comment by rwy7** [comment]
I think the time is here to move next into master. Maybe we can tag the current master branch as `cascon_2016` and `cusec_2017` (which presentations was it used?).

**Comment by youngar** [comment]
pushed `next` to `master`
